# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-29 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('line_notify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('status', models.IntegerField()),
                ('line_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_notify.LineToken')),
            ],
        ),
    ]
