# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-03 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_notify', '0002_coursenotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='linetoken',
            name='state',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='linetoken',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
