# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-10 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_notify', '0003_auto_20190803_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursenotify',
            name='is_notified',
            field=models.IntegerField(default=0),
        ),
    ]
