# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-25 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_notify', '0004_coursenotify_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursenotify',
            name='usage',
            field=models.IntegerField(default=0),
        ),
    ]
